<?php $list = $this->getList() ?>

<div class="mirasvit-profiler__container">
    <table class="wide">
        <thead>
            <tr>
                <th>URL</th>
                <th>Time</th>
            </tr>
        </thead>
        <?php foreach ($list as $file => $meta): ?>
            <tr>
                <td><a href="<?= $this->getUrl('profiler/index/view', ['_query' => ['file' => $file]]) ?>">
                        <?= $meta['url'] ?></a></td>
                <td><?= date('d.m.Y H:i:s', $meta['time']) ?></td>
            </tr>
        <?php endforeach ?>
    </table>
</div>